(function(){
'use strict';
const dictionaries=window.MwestTranslations;
const supported=Object.freeze(['en','ar','bg','zh-CN','zh-TW','cs','da','nl','fi','fr','de','el','he','hi','hu','id','it','ja','ko','nb','pl','pt','ro','ru','sk','es','sv','th','tr','uk','vi']);
function match(value){const tag=String(value||'').replaceAll('_','-').toLowerCase();if((tag==='zh'||tag.startsWith('zh-')))return /(?:^|-)(?:hant|tw|hk|mo)(?:-|$)/.test(tag)?'zh-TW':'zh-CN';const base=tag.split('-')[0];if(base==='no')return'nb';return supported.find(x=>x.toLowerCase()===base)||null}
function code(language){if(language&&language!=='auto')return match(language)||'en';for(const preferred of navigator.languages?.length?navigator.languages:[navigator.language||'en']){const found=match(preferred);if(found)return found}return'en'}
function locale(language){const resolved=code(language),preferred=language&&language!=='auto'?[language]:(navigator.languages?.length?navigator.languages:[navigator.language||'en']);for(const value of preferred){if(match(value)!==resolved)continue;try{if(Intl.DateTimeFormat.supportedLocalesOf([value]).length)return value}catch{}}return resolved}
// A missing locale/key always uses English. Unknown keys remain visible for diagnosis.
function t(key,language,params={}){const dict=dictionaries[code(language)]||dictionaries.en;const value=Object.hasOwn(dict,key)?dict[key]:Object.hasOwn(dictionaries.en,key)?dictionaries.en[key]:key;return String(value).replace(/\{(\w+)\}/g,(token,name)=>{if(!Object.hasOwn(params,name))return token;const param=params[name];return param&&typeof param==='object'&&Object.hasOwn(param,'key')?t(param.key,language):String(param)})}
function direction(language){return ['ar','he'].includes(code(language))?'rtl':'ltr'}
function bind(element,key,language,params={}){element.dataset.i18n=key;element.dataset.i18nParams=JSON.stringify(params);element.textContent=t(key,language,params)}
function languageName(value,language){if(value==='auto')return t('automatic',language);const displayCode=value==='zh-CN'?'zh-Hans':value==='zh-TW'?'zh-Hant':value;try{if(typeof Intl.DisplayNames==='function'){const result=new Intl.DisplayNames([locale(language)],{type:'language',fallback:'none'}).of(displayCode);if(result&&result!==displayCode)return result}}catch{}return t('names.'+value,language)}
function translatePage(language){document.documentElement.lang=code(language);document.documentElement.dir=direction(language);document.title=t('pageTitle',language);document.querySelectorAll('[data-i18n]').forEach(element=>{let params={};try{params=JSON.parse(element.dataset.i18nParams||'{}')}catch{}element.textContent=t(element.dataset.i18n,language,params)});for(const attribute of ['placeholder','aria-label','title'])document.querySelectorAll('[data-i18n-'+attribute+']').forEach(element=>element.setAttribute(attribute,t(element.getAttribute('data-i18n-'+attribute),language)));document.querySelectorAll('#language option').forEach(option=>{option.textContent=languageName(option.value,language)})}
window.MwestI18n={supported,dictionaries,code,locale,t,direction,bind,languageName,translatePage,weather:(language,key)=>t('weather.'+key,language)};
})();
