const FALLBACK={zip:'90061',unit:'fahrenheit',refresh:15,hour12:true,showSeconds:true,dateStyle:'compact',dateFormat:'ddd DD MMM YY',weatherIcon:true,conditionText:true,separator:'  •  ',lineGap:8,fontPreset:'preset',fontFamily:'Arial, sans-serif',customFontName:'',customFontUrl:'',customFontFile:'',customFontData:'',order:['time','date','city','state','weather'],shadow:{color:'#000000',opacity:80,x:3,y:3,blur:10},items:{time:{enabled:true,line:1},date:{enabled:true,line:2},city:{enabled:true,line:2},state:{enabled:true,line:2},weather:{enabled:true,line:2}},lines:[{size:64,weight:900,color:'#fff',opacity:100,align:'center',transform:'none',letterSpacing:1},{size:34,weight:600,color:'#fff',opacity:92,align:'center',transform:'uppercase',letterSpacing:2},{size:30,weight:600,color:'#35e2ca',opacity:100,align:'center',transform:'none',letterSpacing:1},{size:28,weight:500,color:'#f34acb',opacity:100,align:'center',transform:'none',letterSpacing:1}]};
let cfg=decodeConfig(),place={city:'Los Angeles',state:'CA',stateLong:'California',lat:33.9245,lon:-118.2716},weather={temp:null,code:0},weatherTimer;
function normalizeConfig(raw){const out=Object.assign({},FALLBACK,raw||{}),oldItems=raw?.items||{};out.shadow=Object.assign({},FALLBACK.shadow,raw?.shadow||{});out.items=JSON.parse(JSON.stringify(FALLBACK.items));Object.keys(out.items).forEach(k=>Object.assign(out.items[k],oldItems[k]||{}));if(oldItems.location){if(!oldItems.city)Object.assign(out.items.city,oldItems.location);if(!oldItems.state)Object.assign(out.items.state,oldItems.location)}const requested=Array.isArray(raw?.order)?raw.order:FALLBACK.order;out.order=requested.filter(k=>out.items[k]);FALLBACK.order.forEach(k=>{if(!out.order.includes(k))out.order.push(k)});out.lines=FALLBACK.lines.map((x,i)=>Object.assign({},x,(raw?.lines||[])[i]||{}));return out}
function decodeConfig(){try{let s=new URLSearchParams(location.hash.slice(1)).get('c')||new URLSearchParams(location.search).get('c');if(!s)return normalizeConfig({});s=s.replaceAll('-','+').replaceAll('_','/');while(s.length%4)s+='=';const bytes=Uint8Array.from(atob(s),c=>c.charCodeAt(0));return normalizeConfig(JSON.parse(new TextDecoder().decode(bytes)))}catch{return normalizeConfig({})}}
function rgba(hex,a){const n=parseInt(hex.slice(1),16);return `rgba(${n>>16},${n>>8&255},${n&255},${a/100})`}
function condition(code){if(code===0)return['☀️','Clear'];if(code<=2)return['🌤️',code===1?'Mostly clear':'Partly cloudy'];if(code===3)return['☁️','Cloudy'];if(code<=48)return['🌫️','Foggy'];if(code<=57)return['🌦️','Drizzle'];if(code<=67)return['🌧️','Rain'];if(code<=77)return['🌨️','Snow'];if(code<=82)return['🌦️','Rain showers'];if(code<=86)return['🌨️','Snow showers'];if(code<=99)return['⛈️','Thunderstorms'];return['🌡️','Weather']}
function formatTime(d){return new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit',second:cfg.showSeconds?'2-digit':undefined,hour12:cfg.hour12}).format(d)}
function formatDate(d){const monthsLong=['January','February','March','April','May','June','July','August','September','October','November','December'],monthsShort=monthsLong.map(x=>x.slice(0,3)),daysLong=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],daysShort=daysLong.map(x=>x.slice(0,3)),y=d.getFullYear(),map={YYYY:String(y),YY:String(y).slice(-2),MMMM:monthsLong[d.getMonth()],MMM:monthsShort[d.getMonth()],MM:String(d.getMonth()+1).padStart(2,'0'),M:String(d.getMonth()+1),DD:String(d.getDate()).padStart(2,'0'),D:String(d.getDate()),dddd:daysLong[d.getDay()],ddd:daysShort[d.getDay()]};return String(cfg.dateFormat||'ddd DD MMM YY').replace(/YYYY|MMMM|dddd|MMM|ddd|MM|DD|YY|M|D/g,t=>map[t])}
function cityText(){return cfg.cityOverride?.trim()||place.city}
function stateText(){return cfg.stateMode==='long'?place.stateLong:place.state}
function weatherHtml(){const [icon,label]=condition(weather.code);const degree=cfg.unit==='celsius'?'°C':'°F';const bits=[];if(cfg.weatherIcon)bits.push(`<span class="weather-symbol">${icon}</span>`);if(weather.temp!==null)bits.push(`${Math.round(weather.temp)}${degree}`);if(cfg.conditionText)bits.push(label);return bits.join(' ')}
function applyCustomFont(){let link=document.getElementById('customFontStylesheet'),style=document.getElementById('uploadedFontStyle');const family=(cfg.customFontName||'Uploaded Font').replace(/["'\\]/g,'');if(cfg.fontPreset==='custom'&&typeof cfg.customFontData==='string'&&cfg.customFontData.startsWith('data:')){if(link)link.remove();if(!style){style=document.createElement('style');style.id='uploadedFontStyle';document.head.appendChild(style)}style.textContent=`@font-face{font-family:"${family}";src:url("${cfg.customFontData}")}`;return}if(cfg.fontPreset==='custom'&&cfg.customFontFile&&/^fonts\/[A-Za-z0-9._% -]+$/.test(cfg.customFontFile)){if(link)link.remove();if(!style){style=document.createElement('style');style.id='uploadedFontStyle';document.head.appendChild(style)}style.textContent=`@font-face{font-family:"${family}";src:url("${cfg.customFontFile}")}`;return}if(style)style.remove();if(cfg.fontPreset==='custom'&&cfg.customFontUrl){try{const url=new URL(cfg.customFontUrl);if(url.protocol==='https:'||url.protocol==='http:'){if(!link){link=document.createElement('link');link.id='customFontStylesheet';link.rel='stylesheet';document.head.appendChild(link)}if(link.href!==url.href)link.href=url.href}}catch{}}else if(link){link.remove()}}
function render(){const now=new Date(),content={time:formatTime(now),date:formatDate(now),city:cityText(),state:stateText(),weather:weatherHtml()};const root=document.getElementById('clock');applyCustomFont();root.style.gap=cfg.lineGap+'px';root.style.fontFamily=cfg.fontPreset==='custom'&&cfg.customFontName?`"${cfg.customFontName.replaceAll('"','')}", sans-serif`:cfg.fontFamily;const sh=cfg.shadow;root.style.textShadow=`${sh.x}px ${sh.y}px ${sh.blur}px ${rgba(sh.color,sh.opacity)}`;root.innerHTML=[1,2,3,4].map((num,i)=>{const keys=cfg.order.filter(k=>cfg.items[k]?.enabled&&Number(cfg.items[k].line)===num);if(!keys.length)return'';const l=cfg.lines[i];const justify={left:'flex-start',center:'center',right:'flex-end'}[l.align]||'center';return `<div class="clock-line" style="font-size:${l.size}px;font-weight:${l.weight};color:${l.color};opacity:${l.opacity/100};justify-content:${justify};text-transform:${l.transform};letter-spacing:${l.letterSpacing}px">${keys.map(k=>`<span class="clock-item ${k}">${content[k]}</span>`).join(`<span class="separator">${cfg.separator}</span>`)}</div>`}).join('')}
async function updateWeather(){try{const z=await fetch(`https://api.zippopotam.us/us/${cfg.zip}`).then(r=>{if(!r.ok)throw Error('ZIP not found');return r.json()}),p=z.places[0];place={city:p['place name'],state:p['state abbreviation'],stateLong:p.state,lat:Number(p.latitude),lon:Number(p.longitude)};const u=`https://api.open-meteo.com/v1/forecast?latitude=${place.lat}&longitude=${place.lon}&current=temperature_2m,weather_code&temperature_unit=${cfg.unit}&timezone=auto`;const data=await fetch(u).then(r=>r.json());weather={temp:data.current.temperature_2m,code:data.current.weather_code};document.getElementById('error').textContent='';render()}catch(e){document.getElementById('error').textContent='Weather unavailable — clock is still running.';render()}clearTimeout(weatherTimer);weatherTimer=setTimeout(updateWeather,Math.max(5,Number(cfg.refresh))*60000)}
addEventListener('message',e=>{if(e.data?.type==='mwest-clock-config'){cfg=normalizeConfig(e.data.config);render();updateWeather()}});render();updateWeather();setInterval(render,1000);
