const DEFAULTS={version:5,zip:'90061',cityOverride:'',stateMode:'short',locationFormat:'cityState',unit:'fahrenheit',refresh:15,hour12:true,showSeconds:true,dateStyle:'compact',dateFormat:'ddd DD MMM YY',weatherIcon:true,conditionText:true,separator:'  •  ',lineGap:8,fontPreset:'preset',fontFamily:'Arial, sans-serif',customFontName:'',customFontUrl:'',customFontFile:'',customFontData:'',order:['time','date','city','state','weather'],shadow:{color:'#000000',opacity:80,x:3,y:3,blur:10},items:{time:{enabled:true,line:1},date:{enabled:true,line:2},city:{enabled:true,line:2},state:{enabled:true,line:2},weather:{enabled:true,line:2}},lines:[{size:64,weight:900,color:'#ffffff',opacity:100,align:'center',transform:'none',letterSpacing:1},{size:34,weight:600,color:'#ffffff',opacity:92,align:'center',transform:'uppercase',letterSpacing:2},{size:30,weight:600,color:'#35e2ca',opacity:100,align:'center',transform:'none',letterSpacing:1},{size:28,weight:500,color:'#f34acb',opacity:100,align:'center',transform:'none',letterSpacing:1}]};
const ITEM_META={time:['◷','Time'],date:['▣','Date'],city:['⌖','City'],state:['◈','State'],weather:['☀','Weather']};
let state=load(),activeLine=0,previewTimer;
let installedFonts=loadFontCache();
const $=id=>document.getElementById(id);
function clone(x){return JSON.parse(JSON.stringify(x))}
function merge(raw){const d=clone(DEFAULTS);if(!raw)return d;Object.assign(d,raw);d.shadow=Object.assign(clone(DEFAULTS.shadow),raw.shadow||{});const oldItems=raw.items||{};d.items=clone(DEFAULTS.items);Object.keys(d.items).forEach(k=>Object.assign(d.items[k],oldItems[k]||{}));if(oldItems.location){if(!oldItems.city)Object.assign(d.items.city,oldItems.location);if(!oldItems.state)Object.assign(d.items.state,oldItems.location)}const requested=Array.isArray(raw.order)?raw.order:DEFAULTS.order;d.order=requested.filter(k=>d.items[k]);DEFAULTS.order.forEach(k=>{if(!d.order.includes(k))d.order.push(k)});d.lines=DEFAULTS.lines.map((x,i)=>Object.assign(x,(raw.lines||[])[i]||{}));return d}
function load(){try{const params=new URLSearchParams(location.search);if(params.get('reset')==='1'){localStorage.removeItem('mwestClockSettings');localStorage.removeItem('mwestInstalledFonts');history.replaceState({},'',location.pathname);return clone(DEFAULTS)}return merge(JSON.parse(localStorage.getItem('mwestClockSettings')))}catch{return clone(DEFAULTS)}}
function encode(obj){const bytes=new TextEncoder().encode(JSON.stringify(obj));let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function overlayUrl(){const url=new URL('overlay.html',location.href);url.hash='c='+encode(state);return url.href}
function loadFontCache(){try{return JSON.parse(localStorage.getItem('mwestInstalledFonts')||'[]')}catch{return[]}}
function renderFontList(filter=''){const box=$('fontList');if(!box)return;const q=filter.trim().toLowerCase(),uploaded=state.customFontFile&&state.customFontName?[{family:state.customFontName,file:state.customFontFile}]:[],rows=[...uploaded,...installedFonts.filter(f=>!uploaded.some(u=>u.family===f))].filter(x=>(x.family||x).toLowerCase().includes(q));box.innerHTML='';if(!rows.length){box.innerHTML='<div class="font-empty">'+(installedFonts.length?'No fonts match that search.':'Click “Check Installed Fonts” to load your Windows font list.')+'</div>';return}rows.forEach(row=>{const family=row.family||row,b=document.createElement('button');b.type='button';b.textContent=(row.file?'★ ':'')+family;b.dataset.fontFamily=family;if(row.file)b.dataset.fontFile=row.file;b.style.fontFamily='"'+family.replaceAll('"','')+'", sans-serif';b.classList.toggle('selected',state.fontPreset==='custom'&&state.customFontName===family);box.appendChild(b)})}
function renderItems(){ $('items').innerHTML=state.order.map((key,index)=>{const [icon,name]=ITEM_META[key];return `<div class="item-row"><div class="item-icon">${icon}</div><div><div class="item-name">${name}</div><label class="item-toggle"><input data-item-enabled="${key}" type="checkbox" ${state.items[key].enabled?'checked':''}><span></span></label></div><select data-item-line="${key}" aria-label="${name} line">${[1,2,3,4].map(n=>`<option value="${n}" ${state.items[key].line===n?'selected':''}>Line ${n}</option>`).join('')}</select><div class="order-buttons"><button type="button" data-move="-1" data-item-key="${key}" aria-label="Move ${name} up" ${index===0?'disabled':''}>▲</button><button type="button" data-move="1" data-item-key="${key}" aria-label="Move ${name} down" ${index===state.order.length-1?'disabled':''}>▼</button></div></div>`}).join('') }
function renderTabs(){ $('lineTabs').innerHTML=[1,2,3,4].map((n,i)=>`<button data-line-tab="${i}" class="${activeLine===i?'active':''}">LINE ${n}</button>`).join('');renderLineStyle() }
function renderLineStyle(){const l=state.lines[activeLine];$('lineStyle').innerHTML=`<div class="line-style-grid"><label>Font size <span>${l.size}px</span><input data-line-prop="size" type="range" min="12" max="180" value="${l.size}"></label><label>Weight<select data-line-prop="weight">${[300,400,500,600,700,800,900].map(v=>`<option ${l.weight==v?'selected':''} value="${v}">${v}</option>`).join('')}</select></label><label>Color<input data-line-prop="color" type="color" value="${l.color}"></label><label>Opacity <span>${l.opacity}%</span><input data-line-prop="opacity" type="range" min="0" max="100" value="${l.opacity}"></label><label>Alignment<select data-line-prop="align"><option ${l.align==='left'?'selected':''}>left</option><option ${l.align==='center'?'selected':''}>center</option><option ${l.align==='right'?'selected':''}>right</option></select></label><label>Text transform<select data-line-prop="transform"><option value="none" ${l.transform==='none'?'selected':''}>Normal</option><option value="uppercase" ${l.transform==='uppercase'?'selected':''}>UPPERCASE</option><option value="lowercase" ${l.transform==='lowercase'?'selected':''}>lowercase</option></select></label><label class="full">Letter spacing <span>${l.letterSpacing}px</span><input data-line-prop="letterSpacing" type="range" min="-3" max="20" value="${l.letterSpacing}"></label></div>`}
function updateFontPanels(){$('customFontWrap').classList.toggle('hidden',state.fontPreset!=='custom');$('presetFontWrap').classList.toggle('hidden',state.fontPreset==='custom')}
function hydrate(){renderItems();renderTabs();['zip','cityOverride','stateMode','locationFormat','unit','dateStyle','dateFormat','separator','fontPreset','fontFamily','customFontName','customFontUrl'].forEach(id=>$(id).value=state[id]);$('refresh').value=String(state.refresh);$('hour12').value=String(state.hour12);['showSeconds','weatherIcon','conditionText'].forEach(id=>$(id).checked=state[id]);$('lineGap').value=state.lineGap;['shadowColor'].forEach(id=>$(id).value=state.shadow[id.replace('shadow','').toLowerCase()]);['shadowOpacity','shadowX','shadowY','shadowBlur'].forEach(id=>$(id).value=state.shadow[id.slice(6).toLowerCase()]);$('fontUploadStatus').textContent=(state.customFontFile||state.customFontData)?'Loaded: '+(state.customFontName||'custom font'):'No custom font file loaded yet.';renderFontList($('fontSearch')?.value||'');updateFontPanels();outputs()}
function outputs(){ $('lineGapOut').textContent=state.lineGap+'px';['Opacity','X','Y','Blur'].forEach(k=>$("shadow"+k+"Out").textContent=state.shadow[k.toLowerCase()]+(k==='Opacity'?'%':'px')) }
function save(){localStorage.setItem('mwestClockSettings',JSON.stringify(state));outputs();clearTimeout(previewTimer);previewTimer=setTimeout(()=>{const frame=$('preview');if(!frame.src)frame.src=overlayUrl();else frame.contentWindow?.postMessage({type:'mwest-clock-config',config:state},'*')},80)}
function setPreset(name){document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b.dataset.preset===name));if(name==='single'){Object.values(state.items).forEach(x=>{if(x.enabled)x.line=1})}if(name==='stacked'){state.items.time.line=1;['date','city','state','weather'].forEach(k=>state.items[k].line=2)}if(name==='three'){state.items.time.line=1;state.items.date.line=2;['city','state','weather'].forEach(k=>state.items[k].line=3)}if(name==='four'){state.items.time.line=1;state.items.date.line=2;state.items.city.line=3;state.items.state.line=3;state.items.weather.line=4}renderItems();save()}
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.itemEnabled){state.items[t.dataset.itemEnabled].enabled=t.checked;save();return}if(t.dataset.itemLine){state.items[t.dataset.itemLine].line=Number(t.value);save();return}if(t.dataset.lineProp){let v=t.value;if(['size','weight','opacity','letterSpacing'].includes(t.dataset.lineProp))v=Number(v);state.lines[activeLine][t.dataset.lineProp]=v;if(t.type==='range'&&t.previousElementSibling)t.previousElementSibling.textContent=v+(t.dataset.lineProp==='opacity'?'%':'px');save();return}const id=t.id;if(['showSeconds','weatherIcon','conditionText'].includes(id))state[id]=t.checked;else if(id==='hour12')state[id]=t.value==='true';else if(id==='refresh'||id==='lineGap')state[id]=Number(t.value);else if(id.startsWith('shadow'))state.shadow[id.slice(6).toLowerCase()]=id==='shadowColor'?t.value:Number(t.value);else if(id in state)state[id]=t.value;if(id==='fontPreset')updateFontPanels();save()});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.preset){setPreset(b.dataset.preset);return}if(b.dataset.lineTab){activeLine=Number(b.dataset.lineTab);renderTabs();return}if(b.dataset.size){document.querySelectorAll('[data-size]').forEach(x=>x.classList.toggle('active',x===b));$('previewFrame').className='preview-frame '+b.dataset.size;return}if(b.id==='copyUrl'){try{await navigator.clipboard.writeText(overlayUrl());$('copyUrl').textContent='URL COPIED!';setTimeout(()=>$('copyUrl').textContent='COPY OBS URL',1800)}catch{prompt('Copy this OBS URL:',overlayUrl())}}if(b.id==='resetBtn'&&confirm('Reset every clock setting to the defaults?')){localStorage.removeItem('mwestClockSettings');state=clone(DEFAULTS);hydrate();localStorage.setItem('mwestClockSettings',JSON.stringify(state));$('preview').src=overlayUrl();outputs();$('weatherStatus').textContent='Clock restored to default settings.'}if(b.id==='exportBtn'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='mwest-clock-settings.json';a.click();URL.revokeObjectURL(a.href)}if(b.id==='testLocation'){testWeather()}});
$('items').addEventListener('click',e=>{const b=e.target.closest('[data-move]');if(!b)return;const from=state.order.indexOf(b.dataset.itemKey),to=from+Number(b.dataset.move);if(from<0||to<0||to>=state.order.length)return;[state.order[from],state.order[to]]=[state.order[to],state.order[from]];renderItems();save()});
$('locationFormat').addEventListener('change',e=>{state.items.city.enabled=e.target.value!=='state';state.items.state.enabled=e.target.value!=='city';renderItems()});
$('fontSearch').addEventListener('input',e=>renderFontList(e.target.value));
$('scanFonts').addEventListener('click',async()=>{const status=$('fontScanStatus');if(!('queryLocalFonts' in window)){status.textContent='Installed-font scanning needs desktop Chrome or Edge. You can still upload a font file below.';return}status.textContent='Waiting for font permission…';try{const faces=await window.queryLocalFonts();installedFonts=[...new Set(faces.map(f=>f.family).filter(Boolean))].sort((a,b)=>a.localeCompare(b));localStorage.setItem('mwestInstalledFonts',JSON.stringify(installedFonts));renderFontList($('fontSearch').value);status.textContent=installedFonts.length+' installed font families found. Search or click one to apply it.'}catch(err){status.textContent=err.name==='NotAllowedError'?'Font access was not allowed. Click again and choose Allow.':'Could not read installed fonts: '+err.message}});
$('fontList').addEventListener('click',e=>{const b=e.target.closest('[data-font-family]');if(!b)return;state.fontPreset='custom';state.customFontName=b.dataset.fontFamily;state.customFontFile=b.dataset.fontFile||'';state.customFontUrl='';hydrate();save();$('fontScanStatus').textContent='Selected: '+b.dataset.fontFamily});
$('importFile').addEventListener('change',async e=>{try{state=merge(JSON.parse(await e.target.files[0].text()));hydrate();save();$('weatherStatus').textContent='Settings imported successfully.'}catch{$('weatherStatus').textContent='That settings file could not be read.'}e.target.value='' });
$('fontFile').addEventListener('change',async e=>{const file=e.target.files?.[0];const status=$('fontUploadStatus');if(!file)return;const ext=file.name.split('.').pop().toLowerCase();if(!['ttf','otf','woff','woff2'].includes(ext)){status.textContent='Please choose a .ttf, .otf, .woff, or .woff2 file.';e.target.value='';return}const hosted=!['localhost','127.0.0.1'].includes(location.hostname);if(file.size>(hosted?750*1024:10*1024*1024)){status.textContent=hosted?'For a hosted OBS URL, choose a font smaller than 750 KB.':'That font is larger than the 10 MB limit.';e.target.value='';return}status.textContent='Loading '+file.name+'…';try{if(hosted){state.customFontData=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)});state.customFontFile=''}else{const response=await fetch('/upload-font',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Font-Name':encodeURIComponent(file.name)},body:await file.arrayBuffer()});if(!response.ok)throw Error(await response.text()||'Upload failed');const result=await response.json();state.customFontFile=result.path;state.customFontData=''}state.customFontName=file.name.replace(/\.[^.]+$/,'');state.customFontUrl='';state.fontPreset='custom';hydrate();save();status.textContent='Ready: '+file.name+' — copy the updated OBS URL.'}catch(err){status.textContent='Could not load the font: '+err.message}e.target.value=''})
async function testWeather(){const status=$('weatherStatus');status.textContent='Checking ZIP and current weather…';try{const z=await fetch(`https://api.zippopotam.us/us/${state.zip}`).then(r=>{if(!r.ok)throw Error('ZIP not found');return r.json()});const p=z.places[0];const url=`https://api.open-meteo.com/v1/forecast?latitude=${p.latitude}&longitude=${p.longitude}&current=temperature_2m,weather_code&temperature_unit=${state.unit}&timezone=auto`;const w=await fetch(url).then(r=>r.json());status.textContent=`Connected: ${p['place name']}, ${p['state abbreviation']} • ${Math.round(w.current.temperature_2m)}${w.current_units.temperature_2m}`;save()}catch(err){status.textContent=`Could not load weather: ${err.message}`}}
hydrate();$('preview').src=overlayUrl();testWeather();
