const DEFAULTS={version:7,language:'auto',zip:'90061',cityOverride:'',stateMode:'short',locationFormat:'cityState',unit:'fahrenheit',refresh:15,hour12:true,showSeconds:true,dateStyle:'compact',dateFormat:'ddd DD MMM YY',weatherIcon:true,conditionText:true,separator:'  •  ',lineGap:8,fontPreset:'preset',fontFamily:'Arial, sans-serif',customFontName:'',customFontUrl:'',customFontFile:'',customFontData:'',order:['time','date','city','state','weather'],shadow:{color:'#000000',opacity:80,x:3,y:3,blur:10},items:{time:{enabled:true,line:1},date:{enabled:true,line:2},city:{enabled:true,line:2},state:{enabled:true,line:2},weather:{enabled:true,line:2}},itemColors:{time:{enabled:false,color:'#ffffff'},date:{enabled:false,color:'#285cff'},city:{enabled:false,color:'#35e2ca'},state:{enabled:false,color:'#35e2ca'},weather:{enabled:false,color:'#7cff00'}},lines:[{size:64,weight:900,color:'#ffffff',opacity:100,align:'center',transform:'none',letterSpacing:1},{size:34,weight:600,color:'#ffffff',opacity:92,align:'center',transform:'uppercase',letterSpacing:2},{size:30,weight:600,color:'#35e2ca',opacity:100,align:'center',transform:'none',letterSpacing:1},{size:28,weight:500,color:'#f34acb',opacity:100,align:'center',transform:'none',letterSpacing:1}]};
const ITEM_META={time:['◷','Time'],date:['▣','Date'],city:['⌖','City'],state:['◈','State'],weather:['☀','Weather']};
let state=load(),activeLine=0,previewTimer;
let installedFonts=loadFontCache();
let uploadedFonts=loadUploadedFontLibrary();
restoreSelectedUploadedFont();
state.customFontData='';state.customFontFile='';state.customFontUrl='';
let savedState=clone(state),isDirty=false;
const $=id=>document.getElementById(id);
function clone(x){return JSON.parse(JSON.stringify(x))}
function merge(raw){const d=clone(DEFAULTS);if(!raw)return d;Object.assign(d,raw);d.shadow=Object.assign(clone(DEFAULTS.shadow),raw.shadow||{});const oldItems=raw.items||{};d.items=clone(DEFAULTS.items);Object.keys(d.items).forEach(k=>Object.assign(d.items[k],oldItems[k]||{}));if(oldItems.location){if(!oldItems.city)Object.assign(d.items.city,oldItems.location);if(!oldItems.state)Object.assign(d.items.state,oldItems.location)}d.itemColors=clone(DEFAULTS.itemColors);Object.keys(d.itemColors).forEach(k=>Object.assign(d.itemColors[k],raw.itemColors?.[k]||{}));const requested=Array.isArray(raw.order)?raw.order:DEFAULTS.order;d.order=requested.filter(k=>d.items[k]);DEFAULTS.order.forEach(k=>{if(!d.order.includes(k))d.order.push(k)});d.lines=DEFAULTS.lines.map((x,i)=>Object.assign(x,(raw.lines||[])[i]||{}));return d}
function load(){try{const params=new URLSearchParams(location.search);if(params.get('reset')==='1'){localStorage.removeItem('mwestClockSettings');localStorage.removeItem('mwestInstalledFonts');history.replaceState({},'',location.pathname);return clone(DEFAULTS)}return merge(JSON.parse(localStorage.getItem('mwestClockSettings')))}catch{return clone(DEFAULTS)}}
function encode(obj){const bytes=new TextEncoder().encode(JSON.stringify(obj));let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function overlayUrl(config=savedState){const url=new URL('overlay.html',location.href);url.hash='c='+encode(config);return url.href}
function loadFontCache(){try{return JSON.parse(localStorage.getItem('mwestInstalledFonts')||'[]')}catch{return[]}}
function loadUploadedFontLibrary(){try{let list=JSON.parse(localStorage.getItem('mwestUploadedFonts')||'[]');if(!Array.isArray(list))list=[];const saved=JSON.parse(localStorage.getItem('mwestClockSettings')||'null');if(saved?.customFontData&&saved?.customFontName&&!list.some(f=>f.family===saved.customFontName)){list.push({family:saved.customFontName,data:saved.customFontData});localStorage.setItem('mwestUploadedFonts',JSON.stringify(list))}return list.filter(f=>f&&f.family&&typeof f.data==='string'&&f.data.startsWith('data:'))}catch{return[]}}
function saveUploadedFontLibrary(){localStorage.setItem('mwestUploadedFonts',JSON.stringify(uploadedFonts))}
function rememberUploadedFont(family,data){const next=uploadedFonts.filter(f=>f.family!==family);next.unshift({family,data});const serialized=JSON.stringify(next);if(serialized.length>2800000)throw Error('Your saved font library is full. Remove an uploaded font before adding another.');localStorage.setItem('mwestUploadedFonts',serialized);uploadedFonts=next}
function restoreSelectedUploadedFont(){if(state.customFontName&&!state.customFontData){const saved=uploadedFonts.find(f=>f.family===state.customFontName);if(saved){state.customFontData=saved.data;state.customFontFile='';state.fontPreset='custom'}}}
function syncUploadedFontStyles(){let style=document.getElementById('uploadedFontLibraryStyles');if(!style){style=document.createElement('style');style.id='uploadedFontLibraryStyles';document.head.appendChild(style)}style.textContent=uploadedFonts.map(f=>{const family=f.family.replace(/["'\\]/g,'');return '@font-face{font-family:"'+family+'";src:url("'+f.data+'")}'}).join('\n')}
function renderFontList(filter=''){const box=$('fontList');if(!box)return;const q=filter.trim().toLowerCase(),rows=installedFonts.filter(x=>(x.family||x).toLowerCase().includes(q));box.innerHTML='';if(!rows.length){box.innerHTML='<div class="font-empty">'+(installedFonts.length?'No installed fonts match that search.':'Click “Refresh Installed Fonts” to load your Windows font list.')+'</div>';return}rows.forEach(row=>{const family=row.family||row,b=document.createElement('button');b.type='button';b.textContent=family;b.dataset.fontFamily=family;b.style.fontFamily='"'+family.replaceAll('"','')+'", sans-serif';b.classList.toggle('selected',state.fontPreset==='custom'&&state.customFontName===family);box.appendChild(b)})}
function renderItems(){ $('items').innerHTML=state.order.map((key,index)=>{const [icon,name]=ITEM_META[key];return `<div class="item-row"><div class="item-icon">${icon}</div><div><div class="item-name">${name}</div><label class="item-toggle"><input data-item-enabled="${key}" type="checkbox" ${state.items[key].enabled?'checked':''}><span></span></label></div><select data-item-line="${key}" aria-label="${name} line">${[1,2,3,4].map(n=>`<option value="${n}" ${state.items[key].line===n?'selected':''}>Line ${n}</option>`).join('')}</select><div class="order-buttons"><button type="button" data-move="-1" data-item-key="${key}" aria-label="Move ${name} up" ${index===0?'disabled':''}>▲</button><button type="button" data-move="1" data-item-key="${key}" aria-label="Move ${name} down" ${index===state.order.length-1?'disabled':''}>▼</button></div></div>`}).join('') }
function renderItemColors(){$('itemColors').innerHTML=state.order.map(key=>{const [icon,name]=ITEM_META[key],c=state.itemColors[key];return `<div class="item-color-row"><div class="item-color-name"><span>${icon}</span><strong>${name}</strong></div><label class="item-color-toggle"><input data-item-color-enabled="${key}" type="checkbox" ${c.enabled?'checked':''}> Use custom color</label><input data-item-color="${key}" type="color" value="${c.color}" aria-label="${name} color" ${c.enabled?'':'disabled'}></div>`}).join('')}
function renderTabs(){ $('lineTabs').innerHTML=[1,2,3,4].map((n,i)=>`<button data-line-tab="${i}" class="${activeLine===i?'active':''}">LINE ${n}</button>`).join('');renderLineStyle() }
function renderLineStyle(){const l=state.lines[activeLine];$('lineStyle').innerHTML=`<div class="line-style-grid"><label>Font size <span>${l.size}px</span><input data-line-prop="size" type="range" min="12" max="180" value="${l.size}"></label><label>Weight<select data-line-prop="weight">${[300,400,500,600,700,800,900].map(v=>`<option ${l.weight==v?'selected':''} value="${v}">${v}</option>`).join('')}</select></label><label>Color<input data-line-prop="color" type="color" value="${l.color}"></label><label>Opacity <span>${l.opacity}%</span><input data-line-prop="opacity" type="range" min="0" max="100" value="${l.opacity}"></label><label>Alignment<select data-line-prop="align"><option ${l.align==='left'?'selected':''}>left</option><option ${l.align==='center'?'selected':''}>center</option><option ${l.align==='right'?'selected':''}>right</option></select></label><label>Text transform<select data-line-prop="transform"><option value="none" ${l.transform==='none'?'selected':''}>Normal</option><option value="uppercase" ${l.transform==='uppercase'?'selected':''}>UPPERCASE</option><option value="lowercase" ${l.transform==='lowercase'?'selected':''}>lowercase</option></select></label><label class="full">Letter spacing <span>${l.letterSpacing}px</span><input data-line-prop="letterSpacing" type="range" min="-3" max="20" value="${l.letterSpacing}"></label></div>`}
function applyUiLanguage(){MwestI18n.translatePage(state.language)}
function updateFontPanels(){$('customFontWrap').classList.toggle('hidden',state.fontPreset!=='custom');$('presetFontWrap').classList.toggle('hidden',state.fontPreset==='custom')}
function hydrate(){renderItems();renderItemColors();renderTabs();['language','zip','cityOverride','stateMode','locationFormat','unit','dateFormat','separator','fontPreset','fontFamily','customFontName','customFontUrl'].forEach(id=>$(id).value=state[id]);$('refresh').value=String(state.refresh);$('hour12').value=String(state.hour12);['showSeconds','weatherIcon','conditionText'].forEach(id=>$(id).checked=state[id]);$('lineGap').value=state.lineGap;['shadowColor'].forEach(id=>$(id).value=state.shadow[id.replace('shadow','').toLowerCase()]);['shadowOpacity','shadowX','shadowY','shadowBlur'].forEach(id=>$(id).value=state.shadow[id.slice(6).toLowerCase()]);$('fontUploadStatus').textContent=(state.customFontFile||state.customFontData)?'Loaded: '+(state.customFontName||'custom font'):'No custom font file loaded yet.';$('removeUploadedFont').classList.toggle('hidden',!(state.customFontFile||state.customFontData));renderFontList($('fontSearch')?.value||'');updateFontPanels();outputs();applyUiLanguage()}
function outputs(){ $('lineGapOut').textContent=state.lineGap+'px';['Opacity','X','Y','Blur'].forEach(k=>$("shadow"+k+"Out").textContent=state.shadow[k.toLowerCase()]+(k==='Opacity'?'%':'px')) }
function save(){const persisted=clone(state);persisted.customFontData='';persisted.customFontFile='';persisted.customFontUrl='';localStorage.setItem('mwestClockSettings',JSON.stringify(persisted));isDirty=true;$('copyStatus').textContent='Unsaved changes — click Save Settings';outputs();clearTimeout(previewTimer);previewTimer=setTimeout(()=>{const frame=$('preview');if(!frame.src)frame.src=overlayUrl(state);else frame.contentWindow?.postMessage({type:'mwest-clock-config',config:state},'*')},80)}
function setPreset(name){document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b.dataset.preset===name));if(name==='single'){Object.values(state.items).forEach(x=>{if(x.enabled)x.line=1})}if(name==='stacked'){state.items.time.line=1;['date','city','state','weather'].forEach(k=>state.items[k].line=2)}if(name==='three'){state.items.time.line=1;state.items.date.line=2;['city','state','weather'].forEach(k=>state.items[k].line=3)}if(name==='four'){state.items.time.line=1;state.items.date.line=2;state.items.city.line=3;state.items.state.line=3;state.items.weather.line=4}renderItems();save()}
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.itemColorEnabled){state.itemColors[t.dataset.itemColorEnabled].enabled=t.checked;renderItemColors();applyUiLanguage();save();return}if(t.dataset.itemColor){state.itemColors[t.dataset.itemColor].color=t.value;save();return}if(t.dataset.itemEnabled){state.items[t.dataset.itemEnabled].enabled=t.checked;save();return}if(t.dataset.itemLine){state.items[t.dataset.itemLine].line=Number(t.value);save();return}if(t.dataset.lineProp){let v=t.value;if(['size','weight','opacity','letterSpacing'].includes(t.dataset.lineProp))v=Number(v);state.lines[activeLine][t.dataset.lineProp]=v;if(t.type==='range'&&t.previousElementSibling)t.previousElementSibling.textContent=v+(t.dataset.lineProp==='opacity'?'%':'px');save();return}const id=t.id;if(['showSeconds','weatherIcon','conditionText'].includes(id))state[id]=t.checked;else if(id==='hour12')state[id]=t.value==='true';else if(id==='refresh'||id==='lineGap')state[id]=Number(t.value);else if(id.startsWith('shadow'))state.shadow[id.slice(6).toLowerCase()]=id==='shadowColor'?t.value:Number(t.value);else if(id in state)state[id]=t.value;if(id==='fontPreset')updateFontPanels();if(id==='language'){renderItems();renderItemColors();renderTabs();applyUiLanguage()}save()});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.preset){setPreset(b.dataset.preset);return}if(b.dataset.lineTab){activeLine=Number(b.dataset.lineTab);renderTabs();return}if(b.dataset.size){document.querySelectorAll('[data-size]').forEach(x=>x.classList.toggle('active',x===b));$('previewFrame').className='preview-frame '+b.dataset.size;return}if(b.id==='saveBtn'){savedState=clone(state);savedState.customFontData='';savedState.customFontFile='';savedState.customFontUrl='';localStorage.setItem('mwestClockSettings',JSON.stringify(savedState));isDirty=false;$('preview').src=overlayUrl(savedState);$('copyStatus').textContent='Settings saved — ready to copy';$('saveBtn').textContent='SAVED!';setTimeout(()=>$('saveBtn').textContent='SAVE SETTINGS',1500);return}if(b.id==='copyUrl'){if(isDirty){$('copyStatus').textContent='Please click Save Settings before copying';return}try{await navigator.clipboard.writeText(overlayUrl(savedState));$('copyUrl').textContent='URL COPIED!';setTimeout(()=>$('copyUrl').textContent='COPY OBS URL',1800)}catch{prompt('Copy this OBS URL:',overlayUrl(savedState))}return}if(b.id==='resetBtn'&&confirm('Reset every clock setting to the defaults?')){localStorage.removeItem('mwestClockSettings');state=clone(DEFAULTS);state.customFontData='';state.customFontFile='';state.customFontUrl='';savedState=clone(state);isDirty=false;hydrate();localStorage.setItem('mwestClockSettings',JSON.stringify(savedState));$('preview').src=overlayUrl(savedState);outputs();$('weatherStatus').textContent='Clock restored to default settings.';$('copyStatus').textContent='Settings reset and saved'}if(b.id==='exportBtn'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='mwest-clock-settings.json';a.click();URL.revokeObjectURL(a.href)}if(b.id==='testLocation'){testWeather()}});
$('items').addEventListener('click',e=>{const b=e.target.closest('[data-move]');if(!b)return;const from=state.order.indexOf(b.dataset.itemKey),to=from+Number(b.dataset.move);if(from<0||to<0||to>=state.order.length)return;[state.order[from],state.order[to]]=[state.order[to],state.order[from]];renderItems();renderItemColors();applyUiLanguage();save()});
$('locationFormat').addEventListener('change',e=>{state.items.city.enabled=e.target.value!=='state';state.items.state.enabled=e.target.value!=='city';renderItems()});
$('fontSearch').addEventListener('input',e=>renderFontList(e.target.value));
$('scanFonts').addEventListener('click',async()=>{const status=$('fontScanStatus');if(!('queryLocalFonts' in window)){status.textContent='Installed-font scanning needs desktop Chrome or Edge. You can still upload a font file below.';return}status.textContent='Waiting for font permission…';try{const faces=await window.queryLocalFonts();installedFonts=[...new Set(faces.map(f=>f.family).filter(Boolean))].sort((a,b)=>a.localeCompare(b));localStorage.setItem('mwestInstalledFonts',JSON.stringify(installedFonts));renderFontList($('fontSearch').value);status.textContent=installedFonts.length+' installed font families found. Search or click one to apply it.'}catch(err){status.textContent=err.name==='NotAllowedError'?'Font access was not allowed. Click again and choose Allow.':'Could not read installed fonts: '+err.message}});
$('fontList').addEventListener('click',e=>{const b=e.target.closest('[data-font-family]');if(!b)return;state.fontPreset='custom';state.customFontName=b.dataset.fontFamily;state.customFontFile='';state.customFontData='';state.customFontUrl='';hydrate();save();$('fontScanStatus').textContent='Selected installed font: '+b.dataset.fontFamily+'. Restart OBS if it was installed while OBS was open.'});
$('importFile').addEventListener('change',async e=>{try{state=merge(JSON.parse(await e.target.files[0].text()));hydrate();save();$('weatherStatus').textContent='Settings imported successfully.'}catch{$('weatherStatus').textContent='That settings file could not be read.'}e.target.value='' });

async function testWeather(){const status=$('weatherStatus');status.textContent='Checking ZIP and current weather…';try{const z=await fetch(`https://api.zippopotam.us/us/${state.zip}`).then(r=>{if(!r.ok)throw Error('ZIP not found');return r.json()});const p=z.places[0];const url=`https://api.open-meteo.com/v1/forecast?latitude=${p.latitude}&longitude=${p.longitude}&current=temperature_2m,weather_code&temperature_unit=${state.unit}&timezone=auto`;const w=await fetch(url).then(r=>r.json());status.textContent=`Connected: ${p['place name']}, ${p['state abbreviation']} • ${Math.round(w.current.temperature_2m)}${w.current_units.temperature_2m}`}catch(err){status.textContent=`Could not load weather: ${err.message}`}}
hydrate();$('preview').src=overlayUrl();testWeather();
